version: '3.5'

services:
  protonwire:
    container_name: protonwire
    image: "ghcr.io/tprasadtp/protonwire:latest"
    init: true
    restart: always
    environment:
      PROTONVPN_SERVER: ${PROTONVPN_SERVER}
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      DEBUG: "1"
      # KILL_SWITCH: "1"
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv4.conf.all.rp_filter: 2
      net.ipv6.conf.all.disable_ipv6: 1
    volumes:
      - ./entrypoint.sh:/app/entrypoint.sh
    ports:
      - ${EXPOSE_PROXY_PORT}:1080
    mem_limit: 200m
    mem_reservation: 100m
    cpus: 0.1

  socks5:
    restart: always
    container_name: socks5
    image: serjs/go-socks5-proxy
    mem_limit: 200m
    mem_reservation: 100m
    cpus: 0.1
    network_mode: service:protonwire
    environment:
      ALLOWED_IPS: ${ALLOWED_IPS}
      PROXY_PORT: "1080"
